package com.example.demo.service;

import com.example.demo.models.Dog;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.stereotype.Service;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import okhttp3.*;
import io.github.cdimascio.dotenv.Dotenv;

@Service
public class APIService {

    // Fetch the API keys from the .env file
    private static final Dotenv dotenv = Dotenv.load();
    String dogBreedApiKey = dotenv.get("THE_DOG_API_KEY");
    String openAiApiKey = dotenv.get("OPENAI_API_KEY");

    // urls for api calls
    private static final String DOG_BREEDS_URL = "https://api.thedogapi.com/v1/breeds";
    private static final String OPENAI_API_URL = "https://api.openai.com/v1/chat/completions";

    private List<Dog> cachedDogs = new ArrayList<>();

    /**
     * Fetches information about dog breeds from the Dog API and caches the result.
     * <p>
     * This method sends a GET request to the Dog API to retrieve a list of dog breeds.
     * If the data has already been fetched and cached, it returns the cached data.
     * Otherwise, it makes an API call, processes the response, and caches the result for future use.
     *<p>
     * The API response is expected to return a JSON array of dog breed information,
     * which is then deserialized into a list of {@link Dog} objects.
     *<p>
     * If the request fails or an error occurs during the response parsing, an {@link IOException} is thrown.
     *
     * @return A list of {@link Dog} objects containing information about various dog breeds.
     * @throws IOException If the API call fails, or if an error occurs during the response parsing.
     */
    public List<Dog> fetchBreedsInformation() throws IOException{
        if (cachedDogs.isEmpty()) {

            // from postman
            try {
                OkHttpClient client = new OkHttpClient()
                        .newBuilder()
                        .build();

                Request request = new Request.Builder()
                        .url(DOG_BREEDS_URL)
                        .addHeader("x-api-key", dogBreedApiKey)
                        .build();
                Response response = client.newCall(request).execute();

                //ensure call is successful and parse data
                if (response.isSuccessful()) {
                    String responseBody = response.body().string();
                    ObjectMapper om = new ObjectMapper();
                    cachedDogs = om.readValue(responseBody, new TypeReference<>() {
                    });
                    System.out.println("Called API");
                } else {
                    System.out.println("API failed");
                    throw new IOException("Error: " + response.code());
                }
            } catch (IOException e) {
                System.out.println("API failed");
                System.out.println(e.getMessage());
                throw new IOException("Request failed: " + e.getMessage());
            }
        }
        return cachedDogs;
    }

    /**
     * Sends a message to the OpenAI GPT model and retrieves the response.
     * <p>
     * This method constructs a JSON payload with the user message, sends it as a POST request to the OpenAI API (GPT-4 model),
     * and processes the response to extract the content of the generated reply.
     * <p>
     * For more details on integrating the ChatGPT API with Java, see:
     * <a href="https://rollbar.com/blog/how-to-use-chatgpt-api-with-java/">Learn More!</a>
     *
     * @param userMessage The message from the user to be sent to the GPT-4 model.
     * @return The content of the response generated by the GPT-4 model.
     * @throws IOException If an error occurs during the request or response parsing.
     */
    public String sendMessageToGPT(String userMessage) throws IOException {
        OkHttpClient client = new OkHttpClient();

        // format message and select model
        String json = "{"
                + "\"model\": \"gpt-4\","
                + "\"messages\": ["
                + "{"
                + "\"role\": \"user\","
                + "\"content\": \"" + userMessage + "\""
                + "}"
                + "],"
                + "\"max_tokens\": 100"
                + "}";

        RequestBody body = RequestBody.create(json, MediaType.get("application/json; charset=utf-8"));

        Request request = new Request.Builder()
                .url(OPENAI_API_URL)
                .post(body)
                .addHeader("Authorization", "Bearer " + openAiApiKey)
                .build();

        // attempt the request and parse using jackson
        try (Response response = client.newCall(request).execute()) {
            if (response.isSuccessful()) {

                //parse the data to send back to user
                String responseBody = response.body().string();
                ObjectMapper objectMapper = new ObjectMapper();
                JsonNode rootNode = objectMapper.readTree(responseBody);
                JsonNode contentNode = rootNode.path("choices").get(0).path("message").path("content");

                return contentNode.asText();
            } else {
                throw new IOException("Request failed with status: " + response.code());
            }
        }
    }

}



